name: Building Test Reports

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-java@v3
        with:
          java-version: '16'

      - uses: actions/cache@v2
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-maven-

      - name: Run Mutation Testing
        run: mvn package -Ppitest org.pitest:pitest-maven:mutationCoverage